#!/usr/bin/env bash

wget -O ./gcm.deb https://github.com/git-ecosystem/git-credential-manager/releases/download/v2.6.1/gcm-linux_amd64.2.6.1.deb

sudo apt install ./gcm.deb pass -y
rm ./gcm.deb

git config --global credential.credentialStore gpg

pass init "Bernardo Costa Nascimento <bernardoc1104@gmail.com>"

gpg --gen-key
