#!/usr/bin/env bash

git clone -b v0.11.2 https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo apt install ninja-build gettext cmake curl build-essential lua5.1 liblua5.1-0-dev -y

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install