#!/usr/bin/env bash

wget -O flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.32.5-stable.tar.xz

tar -xf ./flutter.tar.xz -C ~/
rm ./flutter.tar.xz

echo 'export PATH="$HOME/flutter/bin:$PATH"' >> ~/.zshenv

sudo apt install cmake clang ninja-build libgtk-3-dev -y

source ~/.zshenv

flutter doctor --android-licenses

flutter doctor
