#!/usr/bin/env bash

wget -O dotnet.tar.gz https://builds.dotnet.microsoft.com/dotnet/Sdk/8.0.411/dotnet-sdk-8.0.411-osx-arm64.tar.gz

mkdir ~/Applications/.dotnet
tar -xf "dotnet.tar.gz" -C ~/Applications/.dotnet/

chdir ~/Applications/.dotnet
./dotnet --info
