#!/usr/bin/env bash

wget https://go.dev/dl/go1.24.4.darwin-arm64.tar.gz

sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.24.4.darwin-arm64.tar.gz

if [[ "$PATH" != *"/usr/local/go/bin" ]]; then
    export PATH=$PATH:/usr/local/go/bin
fi

rm -rf ./go1.24.4.darwin-arm64.tar.gz

go version