#!/usr/bin/env bash

brew install tmux

wget https://release.files.ghostty.org/1.1.3/Ghostty.dmg

hdiutil attach Ghostty.dmg
sudo cp -r /Volumes/Ghostty /Applications
hdiutil detach /Volumes/Ghostty

rm Ghostty.dmg
